### ISSUE TITLE
网页上的contains 没有起作用

### ISSUE THREAD

**Issue by hope1234567hope** [vogo/logtail#8]
请问，网页上的contains:   这个怎么用？   break word 和inline怎么用？
网页上输出的是tail -f  所有的日志，不是要过滤的日志内容啊？
比如：
      "matchers": [
        {
          "contains": [
            "mysqld"
          ],
          "not_contains": [
            "systemd"
          ]

但是网页上显示了tail -f  ***.log中的所有内容？网页上的contains: 似乎没有用？
但 ./logtail logtail-tail-to-console.json显示的仅仅是含mysqld的日志，是正确的。

**Comment by wongoo** [comment]
@hope1234567hope 问题收到，我尽快看一下。 想确认一下你现在用的什么版本，有没有截图？

**Comment by wongoo** [comment]
@hope1234567hope 迭代版本网页功能不小心删除了，我修复了一下，按照下面步骤测试可以。

```bash
GOBIN=$(pwd) go install github.com/vogo/logtail@master
```

config.json
```json
{
  "port": 54321,
  "default_format": {
    "prefix": "!!!!-!!-!!"
  },
  "statistic_period_minutes": 0,
  "transfers": {
    "console": {
      "type": "console"
    }
  },
  "routers": {
    "error-router": {
      "matchers": [
        {
          "contains": [
            "ERROR"
          ],
          "not_contains": [
            "Normal"
          ]
        }
      ],
      "transfers": [
        "console"
      ]
    }
  },
  "servers": {
    "xxx-service-log": {
      "routers": [
        "error-router"
      ],
      "file": {
        "path": "/test/logs",
        "method": "timer",
        "prefix": "",
        "suffix": ".log",
        "recursive": true,
        "dir_file_count_limit": 256
      }
    }
  }
}
```

start logtail: 
```bash
./logtail -file config.json
```

browse http://localhost:54321/index/xxx-service-log

**Comment by hope1234567hope** [comment]
谢谢，你好。因为限制，所以上github困难！
你的工具很好，可否加你的qq之类的，好向你请教！我的qq 3319108413

**Comment by wongoo** [comment]
the issue is fixed, pls use the latest version https://github.com/vogo/logtail/releases/tag/v1.5.2
